name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build - Node.js
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install
        run: yarn

      - name: Compile
        run: npm run build
